baseurl: ""
url: "https://mir-server.io"
incremental: true
exclude:
  - node_modules
  - "Gemfile*"
  - package.json
  - README.md
  - run
  - yarn.lock
  - "*.log"
  - "gulp*"
  - vendor
  - requirements.txt
  - nginx.conf
include:
  - _status
